stack-overflow:
  database:
    host: localhost
    port: 3306
    database: stackoverflow
    username: root
    password: mysql
  redis:
    host: localhost
    port: 6379
    database: 1
    password: redis
  stack-exchange:
    client-id: 30383
    client-secret: Vse503Tr8d3tu7I4GxYx2w((
    key: rl_HHpU4Eh8GzDZ8D9LiHbpQdg8w
    save-to-json: false
    json-path: E:\courses\CS209A-ComputerSystemDesignAndApplicationsA\project\StackOverflow-Java-Analysis\backend\src\main\resources\data\questions.json
    count: 1000
logging:
  level:
    cn.edu.sustech.stackoverflow: debug
